### ISSUE TITLE
GPU Acceleration of SDF gen

### ISSUE THREAD

**Issue by sjkelly** [sjkelly/Descartes.jl#24]
I looked at CUDA, Vulkan, and OpenCL. It is important this runs on most hardware, so CUDA is not an option initially unless we have several backends, which is not a priority right now. Vulkan compute kernels made my eyes bleed. OpenCL might be the best option for this. 

Open question and testing is whether or not to use CLArrays or OpenCL.

**Comment by scheming-pony** [comment]
In my experience, getting OpenCL to run on my development system (Ubuntu/AMD graphics) has been a PITA.  I'm not really advocating that you change this project now, but it is something to keep in mind.  Libfive uses a parallel CPU threading approach--maybe for the same reason as mine?  I could not get this project running today, and I don't have hours to (maybe) get OpenCL working.  Sorry I don't have any better ideas.

**Comment by sjkelly** [comment]
It should be trivial to support threads. In the meantime, the OpenCL requirement should be soft, since it doesn't support all geometries yet and I also have issues with running on Intel Iris.

In the meantime do you have mesa-opencl-icd installed? Also, which GPU do you have?

**Comment by scheming-pony** [comment]
I'll subscribe to this issue--if you post a message here when OpenCL is made optional, I'll try building Descartes again.

**Comment by scheming-pony** [comment]
To rephrase, I think it is a good to abstract out the physical computation method.  I'm not opposed to OpenCL or anything--it just seems to not be a good use of my time to get it working (or maybe yours in supporting it).

I talked to my wife, who works on supercomputer projects, and one can imagine some of the models (especially the physical ones) running on clusters of CPUs, GPUs, or even FPGAs.  Of course, if you do get OpenCL working, that will test the abstraction.  My wife mentioned MPI as a possible technology to support in the future.

**Comment by sjkelly** [comment]
The problem is that the OpenCL back end is not very abstract. It is a kernel compiler and not a transpiler, so some geometries are unsupported in the OpenCL back end. I only can run it on one out of three of my development environments. I have multithreadin and SIMD working now which had very nice performance gains of 12x on 4 threads. This puts it within the same order of magnitude as the GPU performance for most geometries. The bottleneck is still the meshing component, but I have run into some bugs in the multithreading paradigms with the meshing algorithms that may block this.

**Comment by sjkelly** [comment]
Also OpenMPI is very good alternative for very high resolution solid models. From what I understand Julia has a native distributed arrays mechanism that is similar to OpenMPI. 
 Still the bottleneck will be the memory use in the current implementation.  I have some ideas to minimize the memory allocation from nx*ny*nz to nx*ny*2, but I have to rework Meshing.jl before that is possible.

**Comment by sjkelly** [comment]
@scheming-pony if you want to checkout the `sjk/simp` branch and checkout master for `Meshing`, this should work now. I'm shaking down Meshing a little longer before I tag a new release and merge my branch into Descartes.

**Comment by scheming-pony** [comment]
@sjkelly I'm still here and going to try again--should now I just use master for both Descartes and Meshing?

**Comment by scheming-pony** [comment]
Using master for Descartes/Meshing I got it to build and successfully ran the examples!

**Comment by sjkelly** [comment]
:+1: 

I am hoping to add some docs soon for the user-facing API. There will be some code churn in everything else. Please let me know if you have and questions or feature requests.
